on:
  push:
    branches:
      - foolip/bikeshed-action
name: bikeshed
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: foolip/bikeshed-action@master
      with:
        validate: true
